/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) eocar_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[33] = {12, 6, 0, 12, 24, 24, 24, 24, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[21] = {12, 6, 0, 12, 12, 12, 12, 12, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[45] = {12, 6, 0, 12, 24, 36, 36, 36, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[57] = {12, 6, 0, 12, 24, 36, 48, 48, 48, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s4[69] = {12, 6, 0, 12, 24, 36, 48, 60, 60, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {0, 0, 0};

/* ForwardDyn:(x[12],u[6])->(xdot[12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a6, a7, a8, a9;
  a0=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][3]=a3;
  a4=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][4]=a4;
  a5=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][5]=a5;
  a6=arg[1]? arg[1][0] : 0;
  a7=arg[0]? arg[0][4] : 0;
  a8=cos(a7);
  a9=arg[0]? arg[0][5] : 0;
  a10=cos(a9);
  a11=(a10*a4);
  a9=sin(a9);
  a12=(a8*a3);
  a13=(a9*a12);
  a11=(a11-a13);
  a7=sin(a7);
  a13=(a7*a0);
  a14=arg[0]? arg[0][3] : 0;
  a15=cos(a14);
  a16=(a15*a2);
  a14=sin(a14);
  a17=(a14*a1);
  a16=(a16-a17);
  a17=(a8*a16);
  a13=(a13+a17);
  a17=5.0000000000000000e-01;
  a18=(a10*a12);
  a19=(a9*a4);
  a18=(a18+a19);
  a19=(a17*a18);
  a19=(a13+a19);
  a20=(a11*a19);
  a21=(a7*a3);
  a22=(a21+a5);
  a1=(a15*a1);
  a2=(a14*a2);
  a1=(a1+a2);
  a2=(a10*a1);
  a0=(a8*a0);
  a23=(a7*a16);
  a0=(a0-a23);
  a23=(a9*a0);
  a2=(a2-a23);
  a23=(a22*a2);
  a20=(a20-a23);
  a23=8.0000000000000004e-01;
  a24=(a2*a5);
  a25=(a23*a24);
  a20=(a20+a25);
  a25=-5.0000000000000000e-01;
  a26=arg[1]? arg[1][5] : 0;
  a27=(a18*a11);
  a28=1.2500000000000000e+00;
  a29=(a28*a18);
  a30=(a17*a13);
  a29=(a29+a30);
  a30=(a11*a29);
  a27=(a27-a30);
  a30=(a10*a0);
  a31=(a9*a1);
  a30=(a30+a31);
  a31=(a17*a22);
  a31=(a30-a31);
  a32=(a2*a31);
  a27=(a27-a32);
  a32=(a30*a2);
  a27=(a27+a32);
  a27=(a26-a27);
  a32=(a25*a27);
  a32=(a32/a28);
  a20=(a20+a32);
  a32=(a10*a20);
  a33=(a22*a31);
  a34=(a18*a19);
  a33=(a33-a34);
  a34=(a30*a5);
  a33=(a33-a34);
  a34=(a9*a33);
  a32=(a32-a34);
  a34=(a23*a10);
  a35=(a34*a10);
  a36=casadi_sq(a9);
  a35=(a35+a36);
  a36=(a13*a4);
  a37=(a35*a36);
  a32=(a32-a37);
  a37=(a8*a32);
  a38=(a18*a2);
  a39=(a11*a31);
  a38=(a38-a39);
  a39=(a11*a5);
  a40=(a17*a39);
  a38=(a38+a40);
  a40=1.;
  a41=(a17*a9);
  a42=(a28*a9);
  a42=(a42*a9);
  a43=casadi_sq(a10);
  a42=(a42+a43);
  a43=(a41/a42);
  a44=(a41*a43);
  a40=(a40-a44);
  a0=(a0*a4);
  a44=(a40*a0);
  a45=(a17*a10);
  a46=(a28*a10);
  a47=(a46*a9);
  a48=(a9*a10);
  a47=(a47-a48);
  a48=(a47/a42);
  a49=(a41*a48);
  a45=(a45-a49);
  a21=(a21*a4);
  a49=(a45*a21);
  a44=(a44-a49);
  a38=(a38+a44);
  a44=arg[1]? arg[1][4] : 0;
  a49=(a28*a22);
  a50=(a17*a30);
  a49=(a49-a50);
  a50=(a11*a49);
  a11=(a22*a11);
  a50=(a50-a11);
  a11=(a13*a2);
  a50=(a50-a11);
  a2=(a2*a19);
  a50=(a50+a2);
  a39=(a28*a39);
  a50=(a50+a39);
  a39=(a9*a50);
  a22=(a22*a29);
  a49=(a18*a49);
  a22=(a22-a49);
  a13=(a13*a31);
  a22=(a22+a13);
  a30=(a30*a19);
  a22=(a22-a30);
  a18=(a18*a5);
  a22=(a22-a18);
  a18=(a10*a22);
  a39=(a39+a18);
  a44=(a44-a39);
  a39=(a41*a44);
  a39=(a39/a42);
  a38=(a38+a39);
  a39=(a7*a38);
  a37=(a37+a39);
  a34=(a34*a9);
  a39=(a9*a10);
  a34=(a34-a39);
  a39=(a8*a34);
  a16=(a16*a3);
  a18=(a39*a16);
  a5=(a7*a40);
  a30=(a5*a8);
  a19=(a8*a35);
  a13=(a19*a7);
  a30=(a30-a13);
  a13=(a7*a45);
  a13=(a13*a8);
  a45=(a8*a45);
  a45=(a45*a8);
  a46=(a46*a10);
  a31=casadi_sq(a9);
  a46=(a46+a31);
  a48=(a47*a48);
  a46=(a46-a48);
  a48=(a8*a46);
  a48=(a48*a8);
  a31=(a45/a48);
  a49=(a13*a31);
  a30=(a30-a49);
  a1=(a1*a3);
  a3=(a30*a1);
  a18=(a18-a3);
  a37=(a37+a18);
  a18=arg[1]? arg[1][3] : 0;
  a50=(a10*a50);
  a22=(a9*a22);
  a50=(a50-a22);
  a17=(a17*a10);
  a43=(a47*a43);
  a17=(a17-a43);
  a17=(a17*a0);
  a46=(a46*a21);
  a17=(a17-a46);
  a50=(a50+a17);
  a17=(a47*a44);
  a17=(a17/a42);
  a50=(a50+a17);
  a50=(a8*a50);
  a26=(a7*a26);
  a50=(a50+a26);
  a18=(a18-a50);
  a50=(a13*a18);
  a50=(a50/a48);
  a37=(a37+a50);
  a50=(a39*a14);
  a26=(a30*a15);
  a50=(a50+a26);
  a26=arg[1]? arg[1][2] : 0;
  a20=(a9*a20);
  a33=(a10*a33);
  a20=(a20+a33);
  a23=(a23*a9);
  a33=(a23*a10);
  a17=(a10*a9);
  a33=(a33-a17);
  a17=(a33*a36);
  a20=(a20-a17);
  a23=(a23*a9);
  a17=casadi_sq(a10);
  a23=(a23+a17);
  a17=(a23*a16);
  a46=(a33*a7);
  a43=(a46*a1);
  a17=(a17+a43);
  a20=(a20+a17);
  a17=(a14*a20);
  a38=(a8*a38);
  a32=(a7*a32);
  a38=(a38-a32);
  a34=(a7*a34);
  a32=(a34*a16);
  a35=(a7*a35);
  a43=(a35*a7);
  a40=(a8*a40);
  a22=(a40*a8);
  a43=(a43+a22);
  a31=(a45*a31);
  a43=(a43-a31);
  a31=(a43*a1);
  a32=(a32+a31);
  a38=(a38-a32);
  a32=(a45*a18);
  a32=(a32/a48);
  a38=(a38+a32);
  a32=(a15*a38);
  a17=(a17+a32);
  a26=(a26-a17);
  a17=(a50*a26);
  a32=(a14*a23);
  a31=(a15*a34);
  a32=(a32-a31);
  a31=(a32*a14);
  a22=(a15*a43);
  a3=(a14*a46);
  a22=(a22-a3);
  a3=(a22*a15);
  a31=(a31+a3);
  a17=(a17/a31);
  a37=(a37+a17);
  a39=(a39*a15);
  a30=(a30*a14);
  a39=(a39-a30);
  a23=(a15*a23);
  a34=(a14*a34);
  a23=(a23+a34);
  a34=(a23*a14);
  a46=(a15*a46);
  a43=(a14*a43);
  a46=(a46+a43);
  a43=(a46*a15);
  a34=(a34-a43);
  a43=(a34/a31);
  a30=(a50*a43);
  a39=(a39-a30);
  a30=arg[1]? arg[1][1] : 0;
  a20=(a15*a20);
  a38=(a14*a38);
  a20=(a20-a38);
  a38=(a34*a26);
  a38=(a38/a31);
  a20=(a20+a38);
  a30=(a30-a20);
  a20=(a39*a30);
  a23=(a23*a15);
  a46=(a46*a14);
  a23=(a23+a46);
  a43=(a34*a43);
  a23=(a23-a43);
  a20=(a20/a23);
  a37=(a37+a20);
  a6=(a6-a37);
  a37=9.8100000000000005e+00;
  a33=(a33*a8);
  a33=(a14*a33);
  a40=(a40*a7);
  a35=(a35*a8);
  a40=(a40-a35);
  a35=(a13/a48);
  a20=(a45*a35);
  a40=(a40-a20);
  a40=(a15*a40);
  a33=(a33+a40);
  a33=(a33-a50);
  a32=(a32*a15);
  a22=(a22*a14);
  a32=(a32-a22);
  a32=(a32-a34);
  a22=(a39/a23);
  a40=(a32*a22);
  a33=(a33-a40);
  a33=(a37*a33);
  a6=(a6-a33);
  a19=(a19*a8);
  a5=(a5*a7);
  a19=(a19+a5);
  a35=(a13*a35);
  a19=(a19-a35);
  a35=(a50/a31);
  a35=(a50*a35);
  a19=(a19-a35);
  a22=(a39*a22);
  a19=(a19-a22);
  a6=(a6/a19);
  if (res[0]!=0) res[0][6]=a6;
  a39=(a39*a6);
  a32=(a37*a32);
  a39=(a39+a32);
  a30=(a30-a39);
  a30=(a30/a23);
  if (res[0]!=0) res[0][7]=a30;
  a50=(a50*a6);
  a34=(a34*a30);
  a50=(a50+a34);
  a34=(a37*a31);
  a50=(a50+a34);
  a26=(a26-a50);
  a26=(a26/a31);
  if (res[0]!=0) res[0][8]=a26;
  a13=(a13*a6);
  a37=(a37+a26);
  a26=(a15*a37);
  a31=(a14*a30);
  a26=(a26-a31);
  a26=(a26-a1);
  a45=(a45*a26);
  a13=(a13+a45);
  a18=(a18-a13);
  a18=(a18/a48);
  if (res[0]!=0) res[0][9]=a18;
  a48=(a8*a18);
  a48=(a48-a21);
  a47=(a47*a48);
  a48=(a7*a6);
  a21=(a8*a26);
  a48=(a48+a21);
  a48=(a48+a0);
  a41=(a41*a48);
  a47=(a47+a41);
  a44=(a44-a47);
  a44=(a44/a42);
  if (res[0]!=0) res[0][10]=a44;
  a18=(a7*a18);
  a12=(a12*a4);
  a18=(a18+a12);
  a18=(a28*a18);
  a8=(a8*a6);
  a7=(a7*a26);
  a8=(a8-a7);
  a8=(a8-a36);
  a10=(a10*a8);
  a15=(a15*a30);
  a14=(a14*a37);
  a15=(a15+a14);
  a15=(a15+a16);
  a9=(a9*a15);
  a10=(a10+a9);
  a10=(a10+a24);
  a25=(a25*a10);
  a18=(a18+a25);
  a27=(a27-a18);
  a27=(a27/a28);
  if (res[0]!=0) res[0][11]=a27;
  return 0;
}

/* eocar_ode_expl_ode_fun:(i0[12],i1[6],i2[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real *w0=w+51, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+75, *w14=w+87, *w15=w+111, *w16=w+123, *w17=w+129, *w18=w+141, *w19=w+153, *w20=w+189, *w21=w+237, *w22=w+297;
  /* #0: @0 = zeros(12x6,12nz) */
  casadi_clear(w0, 12);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = input[0][2] */
  w3 = arg[0] ? arg[0][2] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #7: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #8: @8 = input[0][7] */
  w8 = arg[0] ? arg[0][7] : 0;
  /* #9: @9 = input[0][8] */
  w9 = arg[0] ? arg[0][8] : 0;
  /* #10: @10 = input[0][9] */
  w10 = arg[0] ? arg[0][9] : 0;
  /* #11: @11 = input[0][10] */
  w11 = arg[0] ? arg[0][10] : 0;
  /* #12: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #13: @13 = vertcat(@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: (@0[:12] = @13) */
  for (rr=w0+0, ss=w13; rr!=w0+12; rr+=1) *rr = *ss++;
  /* #15: @14 = project(@0) */
  casadi_project(w0, casadi_s1, w14, casadi_s0, w);
  /* #16: @13 = @0[:12] */
  for (rr=w13, ss=w0+0; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #17: @1 = 0.00215054 */
  w1 = 2.1505376344086021e-03;
  /* #18: @15 = @0[:12] */
  for (rr=w15, ss=w0+0; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #19: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #20: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #21: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #22: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #23: @6 = input[1][4] */
  w6 = arg[1] ? arg[1][4] : 0;
  /* #24: @7 = input[1][5] */
  w7 = arg[1] ? arg[1][5] : 0;
  /* #25: @16 = vertcat(@2, @3, @4, @5, @6, @7) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #26: @17 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #27: @15 = @0[:12] */
  for (rr=w15, ss=w0+0; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #28: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #29: @18 = (@2*@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #30: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #31: @18 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #32: @15 = (2.*@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #33: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #34: @15 = @0[:12] */
  for (rr=w15, ss=w0+0; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #35: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #36: @18 = (@2*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #37: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #38: @18 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #39: @15 = (2.*@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #40: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #41: @15 = @0[:12] */
  for (rr=w15, ss=w0+0; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #42: @2 = 0.0129032 */
  w2 = 1.2903225806451613e-02;
  /* #43: @18 = (@2*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #44: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #45: @18 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #46: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #47: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #48: @13 = (@13+@17) */
  for (i=0, rr=w13, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #49: (@14[12:24] = @13) */
  for (rr=w14+12, ss=w13; rr!=w14+24; rr+=1) *rr = *ss++;
  /* #50: @19 = project(@14) */
  casadi_project(w14, casadi_s0, w19, casadi_s2, w);
  /* #51: @13 = @14[12:24] */
  for (rr=w13, ss=w14+12; ss!=w14+24; ss+=1) *rr++ = *ss;
  /* #52: @1 = 0.00215054 */
  w1 = 2.1505376344086021e-03;
  /* #53: @17 = @14[12:24] */
  for (rr=w17, ss=w14+12; ss!=w14+24; ss+=1) *rr++ = *ss;
  /* #54: @18 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #55: @17 = @14[12:24] */
  for (rr=w17, ss=w14+12; ss!=w14+24; ss+=1) *rr++ = *ss;
  /* #56: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #57: @15 = (@2*@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #58: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #59: @15 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #60: @17 = (2.*@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #61: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #62: @17 = @14[12:24] */
  for (rr=w17, ss=w14+12; ss!=w14+24; ss+=1) *rr++ = *ss;
  /* #63: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #64: @15 = (@2*@15) */
  for (i=0, rr=w15, cs=w15; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #65: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #66: @15 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #67: @17 = (2.*@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #68: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #69: @17 = @14[12:24] */
  for (rr=w17, ss=w14+12; ss!=w14+24; ss+=1) *rr++ = *ss;
  /* #70: @2 = 0.0129032 */
  w2 = 1.2903225806451613e-02;
  /* #71: @15 = (@2*@15) */
  for (i=0, rr=w15, cs=w15; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #72: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #73: @15 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #74: @18 = (@18+@15) */
  for (i=0, rr=w18, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #75: @18 = (@1*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #76: @13 = (@13+@18) */
  for (i=0, rr=w13, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #77: (@19[24:36] = @13) */
  for (rr=w19+24, ss=w13; rr!=w19+36; rr+=1) *rr = *ss++;
  /* #78: @20 = project(@19) */
  casadi_project(w19, casadi_s2, w20, casadi_s3, w);
  /* #79: @13 = @19[24:36] */
  for (rr=w13, ss=w19+24; ss!=w19+36; ss+=1) *rr++ = *ss;
  /* #80: @1 = 0.00215054 */
  w1 = 2.1505376344086021e-03;
  /* #81: @18 = @19[24:36] */
  for (rr=w18, ss=w19+24; ss!=w19+36; ss+=1) *rr++ = *ss;
  /* #82: @15 = ForwardDyn(@18, @16) */
  arg1[0]=w18;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #83: @18 = @19[24:36] */
  for (rr=w18, ss=w19+24; ss!=w19+36; ss+=1) *rr++ = *ss;
  /* #84: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #85: @17 = (@2*@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #86: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #87: @17 = ForwardDyn(@18, @16) */
  arg1[0]=w18;
  arg1[1]=w16;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #88: @18 = (2.*@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #89: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #90: @18 = @19[24:36] */
  for (rr=w18, ss=w19+24; ss!=w19+36; ss+=1) *rr++ = *ss;
  /* #91: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #92: @17 = (@2*@17) */
  for (i=0, rr=w17, cs=w17; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #93: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #94: @17 = ForwardDyn(@18, @16) */
  arg1[0]=w18;
  arg1[1]=w16;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #95: @18 = (2.*@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #96: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #97: @18 = @19[24:36] */
  for (rr=w18, ss=w19+24; ss!=w19+36; ss+=1) *rr++ = *ss;
  /* #98: @2 = 0.0129032 */
  w2 = 1.2903225806451613e-02;
  /* #99: @17 = (@2*@17) */
  for (i=0, rr=w17, cs=w17; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #100: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #101: @17 = ForwardDyn(@18, @16) */
  arg1[0]=w18;
  arg1[1]=w16;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #102: @15 = (@15+@17) */
  for (i=0, rr=w15, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #103: @15 = (@1*@15) */
  for (i=0, rr=w15, cs=w15; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #104: @13 = (@13+@15) */
  for (i=0, rr=w13, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #105: (@20[36:48] = @13) */
  for (rr=w20+36, ss=w13; rr!=w20+48; rr+=1) *rr = *ss++;
  /* #106: @21 = project(@20) */
  casadi_project(w20, casadi_s3, w21, casadi_s4, w);
  /* #107: @13 = @20[36:48] */
  for (rr=w13, ss=w20+36; ss!=w20+48; ss+=1) *rr++ = *ss;
  /* #108: @1 = 0.00215054 */
  w1 = 2.1505376344086021e-03;
  /* #109: @15 = @20[36:48] */
  for (rr=w15, ss=w20+36; ss!=w20+48; ss+=1) *rr++ = *ss;
  /* #110: @17 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #111: @15 = @20[36:48] */
  for (rr=w15, ss=w20+36; ss!=w20+48; ss+=1) *rr++ = *ss;
  /* #112: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #113: @18 = (@2*@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #114: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #115: @18 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #116: @15 = (2.*@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #117: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #118: @15 = @20[36:48] */
  for (rr=w15, ss=w20+36; ss!=w20+48; ss+=1) *rr++ = *ss;
  /* #119: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #120: @18 = (@2*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #121: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #122: @18 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #123: @15 = (2.*@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #124: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #125: @15 = @20[36:48] */
  for (rr=w15, ss=w20+36; ss!=w20+48; ss+=1) *rr++ = *ss;
  /* #126: @2 = 0.0129032 */
  w2 = 1.2903225806451613e-02;
  /* #127: @18 = (@2*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #128: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #129: @18 = ForwardDyn(@15, @16) */
  arg1[0]=w15;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #130: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #131: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #132: @13 = (@13+@17) */
  for (i=0, rr=w13, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #133: (@21[48:60] = @13) */
  for (rr=w21+48, ss=w13; rr!=w21+60; rr+=1) *rr = *ss++;
  /* #134: @22 = dense(@21) */
  casadi_densify(w21, casadi_s4, w22, 0);
  /* #135: @13 = @21[48:60] */
  for (rr=w13, ss=w21+48; ss!=w21+60; ss+=1) *rr++ = *ss;
  /* #136: @1 = 0.00215054 */
  w1 = 2.1505376344086021e-03;
  /* #137: @17 = @21[48:60] */
  for (rr=w17, ss=w21+48; ss!=w21+60; ss+=1) *rr++ = *ss;
  /* #138: @18 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #139: @17 = @21[48:60] */
  for (rr=w17, ss=w21+48; ss!=w21+60; ss+=1) *rr++ = *ss;
  /* #140: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #141: @15 = (@2*@18) */
  for (i=0, rr=w15, cs=w18; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #142: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #143: @15 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #144: @17 = (2.*@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #145: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #146: @17 = @21[48:60] */
  for (rr=w17, ss=w21+48; ss!=w21+60; ss+=1) *rr++ = *ss;
  /* #147: @2 = 0.00645161 */
  w2 = 6.4516129032258064e-03;
  /* #148: @15 = (@2*@15) */
  for (i=0, rr=w15, cs=w15; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #149: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #150: @15 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #151: @17 = (2.*@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #152: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #153: @17 = @21[48:60] */
  for (rr=w17, ss=w21+48; ss!=w21+60; ss+=1) *rr++ = *ss;
  /* #154: @2 = 0.0129032 */
  w2 = 1.2903225806451613e-02;
  /* #155: @15 = (@2*@15) */
  for (i=0, rr=w15, cs=w15; i<12; ++i) (*rr++)  = (w2*(*cs++));
  /* #156: @17 = (@17+@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #157: @15 = ForwardDyn(@17, @16) */
  arg1[0]=w17;
  arg1[1]=w16;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #158: @18 = (@18+@15) */
  for (i=0, rr=w18, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #159: @18 = (@1*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #160: @13 = (@13+@18) */
  for (i=0, rr=w13, cs=w18; i<12; ++i) (*rr++) += (*cs++);
  /* #161: (@22[60:72] = @13) */
  for (rr=w22+60, ss=w13; rr!=w22+72; rr+=1) *rr = *ss++;
  /* #162: @13 = @22[60:72] */
  for (rr=w13, ss=w22+60; ss!=w22+72; ss+=1) *rr++ = *ss;
  /* #163: output[0][0] = @13 */
  casadi_copy(w13, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int eocar_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eocar_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eocar_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eocar_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eocar_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eocar_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eocar_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void eocar_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eocar_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int eocar_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real eocar_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eocar_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eocar_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eocar_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eocar_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eocar_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 369;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
