/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_name_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* adj1_ForwardDyn:(x[12],u[6],p[],out_xdot[12x1,0nz],adj_xdot[12])->(adj_x[12],adj_u[6],adj_p[]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a155, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=cos(a0);
  a2=cos(a0);
  a3=8.0000000000000004e-01;
  a4=arg[0]? arg[0][5] : 0;
  a5=sin(a4);
  a6=(a3*a5);
  a7=cos(a4);
  a8=(a6*a7);
  a9=(a7*a5);
  a8=(a8-a9);
  a9=arg[0]? arg[0][4] : 0;
  a10=sin(a9);
  a11=(a8*a10);
  a12=(a2*a11);
  a13=sin(a0);
  a14=(a3*a7);
  a15=(a14*a7);
  a16=casadi_sq(a5);
  a15=(a15+a16);
  a16=(a10*a15);
  a17=(a16*a10);
  a18=cos(a9);
  a19=1.;
  a20=5.0000000000000000e-01;
  a21=(a20*a5);
  a22=1.2500000000000000e+00;
  a23=(a22*a5);
  a24=(a23*a5);
  a25=casadi_sq(a7);
  a24=(a24+a25);
  a25=(a21/a24);
  a26=(a21*a25);
  a19=(a19-a26);
  a26=(a18*a19);
  a27=(a26*a18);
  a17=(a17+a27);
  a27=(a20*a7);
  a28=(a22*a7);
  a29=(a28*a5);
  a30=(a5*a7);
  a29=(a29-a30);
  a30=(a29/a24);
  a31=(a21*a30);
  a27=(a27-a31);
  a31=(a18*a27);
  a32=(a31*a18);
  a33=(a28*a7);
  a34=casadi_sq(a5);
  a33=(a33+a34);
  a34=(a29*a30);
  a33=(a33-a34);
  a34=(a18*a33);
  a35=(a34*a18);
  a36=(a32/a35);
  a37=(a32*a36);
  a17=(a17-a37);
  a37=(a13*a17);
  a12=(a12+a37);
  a37=(a14*a5);
  a38=(a5*a7);
  a37=(a37-a38);
  a38=(a18*a37);
  a39=(a38*a2);
  a40=(a10*a19);
  a41=(a40*a18);
  a42=(a18*a15);
  a43=(a42*a10);
  a41=(a41-a43);
  a43=(a10*a27);
  a44=(a43*a18);
  a45=(a44*a36);
  a41=(a41-a45);
  a45=(a41*a13);
  a39=(a39-a45);
  a45=(a38*a13);
  a46=(a41*a2);
  a45=(a45+a46);
  a46=(a6*a5);
  a47=casadi_sq(a7);
  a46=(a46+a47);
  a47=(a2*a46);
  a48=(a10*a37);
  a49=(a13*a48);
  a47=(a47+a49);
  a49=(a47*a13);
  a50=(a12*a2);
  a49=(a49-a50);
  a50=(a13*a46);
  a51=(a2*a48);
  a50=(a50-a51);
  a51=(a50*a13);
  a52=(a2*a17);
  a53=(a13*a11);
  a52=(a52-a53);
  a53=(a52*a2);
  a51=(a51+a53);
  a53=(a49/a51);
  a54=(a45*a53);
  a39=(a39-a54);
  a54=arg[1]? arg[1][1] : 0;
  a55=arg[0]? arg[0][10] : 0;
  a56=(a7*a55);
  a57=arg[0]? arg[0][9] : 0;
  a58=(a18*a57);
  a59=(a5*a58);
  a56=(a56-a59);
  a59=arg[0]? arg[0][6] : 0;
  a60=(a10*a59);
  a61=arg[0]? arg[0][8] : 0;
  a62=(a2*a61);
  a63=arg[0]? arg[0][7] : 0;
  a64=(a13*a63);
  a62=(a62-a64);
  a64=(a18*a62);
  a60=(a60+a64);
  a64=(a7*a58);
  a65=(a5*a55);
  a64=(a64+a65);
  a65=(a20*a64);
  a65=(a60+a65);
  a66=(a56*a65);
  a67=(a10*a57);
  a68=arg[0]? arg[0][11] : 0;
  a69=(a67+a68);
  a70=(a2*a63);
  a71=(a13*a61);
  a70=(a70+a71);
  a71=(a7*a70);
  a72=(a18*a59);
  a73=(a10*a62);
  a72=(a72-a73);
  a73=(a5*a72);
  a71=(a71-a73);
  a73=(a69*a71);
  a66=(a66-a73);
  a73=(a71*a68);
  a73=(a3*a73);
  a66=(a66+a73);
  a73=-5.0000000000000000e-01;
  a74=arg[1]? arg[1][5] : 0;
  a75=(a64*a56);
  a76=(a22*a64);
  a77=(a20*a60);
  a76=(a76+a77);
  a77=(a56*a76);
  a75=(a75-a77);
  a77=(a7*a72);
  a78=(a5*a70);
  a77=(a77+a78);
  a78=(a20*a69);
  a78=(a77-a78);
  a79=(a71*a78);
  a75=(a75-a79);
  a79=(a77*a71);
  a75=(a75+a79);
  a75=(a74-a75);
  a75=(a73*a75);
  a75=(a75/a22);
  a66=(a66+a75);
  a75=(a5*a66);
  a79=(a69*a78);
  a80=(a64*a65);
  a79=(a79-a80);
  a80=(a77*a68);
  a79=(a79-a80);
  a80=(a7*a79);
  a75=(a75+a80);
  a80=(a60*a55);
  a81=(a8*a80);
  a75=(a75-a81);
  a81=(a62*a57);
  a82=(a46*a81);
  a83=(a70*a57);
  a84=(a11*a83);
  a82=(a82+a84);
  a75=(a75+a82);
  a82=(a2*a75);
  a84=(a64*a71);
  a85=(a56*a78);
  a84=(a84-a85);
  a85=(a56*a68);
  a86=(a20*a85);
  a84=(a84+a86);
  a86=(a72*a55);
  a87=(a19*a86);
  a88=(a67*a55);
  a89=(a27*a88);
  a87=(a87-a89);
  a84=(a84+a87);
  a87=arg[1]? arg[1][4] : 0;
  a89=(a22*a69);
  a90=(a20*a77);
  a89=(a89-a90);
  a90=(a56*a89);
  a91=(a69*a56);
  a90=(a90-a91);
  a91=(a60*a71);
  a90=(a90-a91);
  a91=(a71*a65);
  a90=(a90+a91);
  a85=(a22*a85);
  a90=(a90+a85);
  a85=(a5*a90);
  a91=(a69*a76);
  a92=(a64*a89);
  a91=(a91-a92);
  a92=(a60*a78);
  a91=(a91+a92);
  a92=(a77*a65);
  a91=(a91-a92);
  a92=(a64*a68);
  a91=(a91-a92);
  a92=(a7*a91);
  a85=(a85+a92);
  a87=(a87-a85);
  a85=(a21*a87);
  a85=(a85/a24);
  a84=(a84+a85);
  a92=(a18*a84);
  a93=(a7*a66);
  a94=(a5*a79);
  a93=(a93-a94);
  a94=(a15*a80);
  a93=(a93-a94);
  a94=(a10*a93);
  a92=(a92-a94);
  a94=(a48*a81);
  a95=(a17*a83);
  a94=(a94+a95);
  a92=(a92-a94);
  a94=arg[1]? arg[1][3] : 0;
  a95=(a7*a90);
  a96=(a5*a91);
  a95=(a95-a96);
  a96=(a20*a7);
  a97=(a29*a25);
  a96=(a96-a97);
  a97=(a96*a86);
  a98=(a33*a88);
  a97=(a97-a98);
  a95=(a95+a97);
  a97=(a29*a87);
  a97=(a97/a24);
  a95=(a95+a97);
  a98=(a18*a95);
  a99=(a10*a74);
  a98=(a98+a99);
  a94=(a94-a98);
  a98=(a32*a94);
  a98=(a98/a35);
  a92=(a92+a98);
  a99=(a13*a92);
  a82=(a82-a99);
  a99=arg[1]? arg[1][2] : 0;
  a100=(a13*a75);
  a101=(a2*a92);
  a100=(a100+a101);
  a99=(a99-a100);
  a100=(a49*a99);
  a100=(a100/a51);
  a82=(a82+a100);
  a54=(a54-a82);
  a82=(a39*a54);
  a101=(a47*a2);
  a102=(a12*a13);
  a101=(a101+a102);
  a102=(a49*a53);
  a101=(a101-a102);
  a82=(a82/a101);
  a102=(a82/a101);
  a103=arg[4]? arg[4][6] : 0;
  a104=8.0000000000000004e-01;
  a105=arg[4]? arg[4][11] : 0;
  a106=(a104*a105);
  a107=(a73*a106);
  a108=(a7*a107);
  a109=(a18*a108);
  a110=arg[4]? arg[4][10] : 0;
  a111=(a110/a24);
  a112=(a21*a111);
  a113=(a10*a112);
  a109=(a109+a113);
  a113=arg[4]? arg[4][9] : 0;
  a114=(a10*a105);
  a115=(a29*a111);
  a116=(a18*a115);
  a114=(a114+a116);
  a113=(a113-a114);
  a114=(a113/a35);
  a116=(a44*a114);
  a109=(a109+a116);
  a116=(a10*a108);
  a117=(a18*a112);
  a116=(a116-a117);
  a117=(a32*a114);
  a116=(a116-a117);
  a117=(a2*a116);
  a118=(a5*a107);
  a119=(a13*a118);
  a117=(a117-a119);
  a119=arg[4]? arg[4][8] : 0;
  a117=(a117+a119);
  a119=(a117/a51);
  a120=(a45*a119);
  a109=(a109+a120);
  a120=arg[4]? arg[4][7] : 0;
  a121=(a2*a118);
  a122=(a13*a116);
  a121=(a121+a122);
  a122=(a49*a119);
  a121=(a121+a122);
  a120=(a120-a121);
  a121=(a120/a101);
  a122=(a39*a121);
  a109=(a109+a122);
  a103=(a103-a109);
  a109=(a42*a18);
  a122=(a40*a10);
  a109=(a109+a122);
  a122=(a44/a35);
  a123=(a44*a122);
  a109=(a109-a123);
  a123=(a45/a51);
  a124=(a45*a123);
  a109=(a109-a124);
  a124=(a39/a101);
  a125=(a39*a124);
  a109=(a109-a125);
  a125=(a103/a109);
  a102=(a102*a125);
  a126=arg[1]? arg[1][0] : 0;
  a127=(a18*a93);
  a128=(a10*a84);
  a127=(a127+a128);
  a128=(a38*a81);
  a129=(a41*a83);
  a128=(a128-a129);
  a127=(a127+a128);
  a128=(a44*a94);
  a128=(a128/a35);
  a127=(a127+a128);
  a129=(a45*a99);
  a129=(a129/a51);
  a127=(a127+a129);
  a127=(a127+a82);
  a126=(a126-a127);
  a127=9.8100000000000005e+00;
  a82=(a8*a18);
  a130=(a13*a82);
  a131=(a26*a10);
  a132=(a16*a18);
  a131=(a131-a132);
  a132=(a32*a122);
  a131=(a131-a132);
  a132=(a2*a131);
  a130=(a130+a132);
  a130=(a130-a45);
  a132=(a50*a2);
  a133=(a52*a13);
  a132=(a132-a133);
  a132=(a132-a49);
  a133=(a132*a124);
  a130=(a130-a133);
  a130=(a127*a130);
  a126=(a126-a130);
  a126=(a126/a109);
  a130=(a39*a126);
  a133=(a127*a132);
  a130=(a130+a133);
  a130=(a54-a130);
  a130=(a130/a101);
  a133=(a130/a101);
  a133=(a133*a120);
  a120=(a124/a101);
  a109=(a126/a109);
  a109=(a109*a103);
  a103=(a39*a109);
  a134=(a127*a125);
  a132=(a132*a134);
  a103=(a103+a132);
  a120=(a120*a103);
  a133=(a133+a120);
  a102=(a102-a133);
  a133=(a12*a102);
  a120=(a45*a126);
  a132=(a49*a130);
  a120=(a120+a132);
  a132=(a127*a51);
  a120=(a120+a132);
  a120=(a99-a120);
  a120=(a120/a51);
  a132=(a127+a120);
  a135=(a132*a118);
  a136=(a130*a116);
  a135=(a135+a136);
  a136=(a124*a134);
  a137=(a127*a121);
  a136=(a136-a137);
  a137=(a52*a136);
  a135=(a135+a137);
  a82=(a82*a134);
  a135=(a135+a82);
  a133=(a133-a135);
  a135=(a125/a101);
  a39=(a39*a135);
  a39=(a121-a39);
  a82=(a92*a39);
  a133=(a133+a82);
  a82=(a13*a102);
  a137=(a130*a119);
  a137=(a137+a136);
  a138=(a53*a102);
  a137=(a137+a138);
  a138=(a39/a51);
  a139=(a99*a138);
  a137=(a137+a139);
  a139=(a49*a102);
  a124=(a124*a109);
  a121=(a126*a121);
  a124=(a124-a121);
  a103=(a103/a101);
  a124=(a124+a103);
  a54=(a54*a135);
  a124=(a124-a54);
  a54=(a45*a124);
  a139=(a139+a54);
  a54=(a139/a51);
  a137=(a137+a54);
  a54=(a2*a137);
  a82=(a82+a54);
  a54=(a17*a82);
  a133=(a133+a54);
  a54=(a47*a137);
  a133=(a133-a54);
  a54=(a2*a102);
  a135=(a13*a137);
  a54=(a54-a135);
  a135=(a48*a54);
  a133=(a133+a135);
  a135=(a41*a124);
  a133=(a133-a135);
  a100=(a100/a51);
  a100=(a100*a39);
  a120=(a120/a51);
  a120=(a120*a117);
  a127=(a127*a119);
  a120=(a120+a127);
  a127=(a123/a51);
  a117=(a45*a109);
  a127=(a127*a117);
  a120=(a120+a127);
  a100=(a100-a120);
  a120=(a53/a51);
  a120=(a120*a139);
  a100=(a100+a120);
  a129=(a129/a51);
  a129=(a129*a125);
  a100=(a100+a129);
  a129=(a2*a100);
  a120=(a13*a136);
  a129=(a129-a120);
  a120=(a11*a129);
  a133=(a133-a120);
  a120=(a50*a100);
  a133=(a133+a120);
  a120=(a2*a136);
  a139=(a13*a100);
  a120=(a120+a139);
  a139=(a46*a120);
  a133=(a133+a139);
  a49=(a49*a138);
  a49=(a119-a49);
  a138=(a125/a51);
  a45=(a45*a138);
  a49=(a49-a45);
  a45=(a75*a49);
  a133=(a133-a45);
  a123=(a123*a109);
  a119=(a126*a119);
  a123=(a123-a119);
  a117=(a117/a51);
  a123=(a123+a117);
  a123=(a123+a134);
  a53=(a53*a124);
  a123=(a123-a53);
  a99=(a99*a138);
  a123=(a123-a99);
  a99=(a38*a123);
  a133=(a133+a99);
  a99=(a41*a125);
  a138=(a13*a39);
  a53=(a2*a49);
  a138=(a138-a53);
  a53=(a17*a138);
  a53=(a116+a53);
  a117=(a2*a39);
  a51=(a13*a49);
  a117=(a117+a51);
  a51=(a11*a117);
  a53=(a53+a51);
  a99=(a99-a53);
  a53=(a57*a99);
  a51=(a138/a35);
  a119=(a32*a51);
  a119=(a114+a119);
  a45=(a125/a35);
  a139=(a44*a45);
  a119=(a119-a139);
  a139=(a18*a119);
  a127=(a5*a139);
  a135=(a139/a24);
  a103=(a29*a135);
  a103=(a111-a103);
  a101=(a18*a138);
  a121=(a10*a125);
  a101=(a101-a121);
  a121=(a101/a24);
  a140=(a21*a121);
  a103=(a103+a140);
  a140=(a7*a103);
  a127=(a127-a140);
  a140=(a64*a127);
  a141=(a7*a139);
  a142=(a5*a103);
  a141=(a141+a142);
  a142=(a56*a141);
  a140=(a140+a142);
  a142=(a20*a140);
  a143=(a65*a127);
  a142=(a142-a143);
  a143=(a10*a138);
  a144=(a18*a125);
  a143=(a143+a144);
  a144=(a5*a143);
  a145=(a7*a117);
  a144=(a144-a145);
  a145=(a68*a144);
  a142=(a142-a145);
  a145=(a5*a117);
  a146=(a7*a143);
  a145=(a145+a146);
  a104=(a104*a145);
  a73=(a73*a104);
  a106=(a106-a73);
  a73=(a71*a106);
  a142=(a142-a73);
  a73=(a60*a127);
  a104=(a56*a101);
  a73=(a73-a104);
  a104=(a69*a144);
  a73=(a73+a104);
  a104=(a71*a106);
  a73=(a73+a104);
  a142=(a142+a73);
  a104=(a5*a142);
  a53=(a53+a104);
  a104=(a60*a141);
  a146=(a65*a141);
  a104=(a104-a146);
  a146=(a64*a101);
  a104=(a104+a146);
  a146=(a77*a106);
  a104=(a104-a146);
  a146=(a78*a106);
  a104=(a104+a146);
  a146=(a3*a145);
  a146=(a107+a146);
  a147=(a68*a146);
  a104=(a104-a147);
  a147=(a69*a145);
  a104=(a104+a147);
  a147=(a7*a104);
  a53=(a53+a147);
  a147=(a61*a53);
  a133=(a133+a147);
  a147=(a78*a127);
  a148=(a71*a141);
  a147=(a147+a148);
  a148=(a8*a117);
  a148=(a108+a148);
  a149=(a15*a143);
  a148=(a148+a149);
  a149=(a55*a148);
  a147=(a147+a149);
  a149=(a69*a127);
  a150=(a56*a106);
  a149=(a149+a150);
  a150=(a20*a149);
  a147=(a147+a150);
  a150=(a77*a127);
  a151=(a71*a141);
  a150=(a150+a151);
  a151=(a64*a144);
  a150=(a150+a151);
  a151=(a56*a145);
  a150=(a150+a151);
  a147=(a147-a150);
  a151=(a18*a147);
  a152=(a48*a138);
  a152=(a118+a152);
  a153=(a46*a117);
  a152=(a152+a153);
  a153=(a38*a125);
  a152=(a152+a153);
  a153=(a57*a152);
  a154=(a19*a101);
  a96=(a96*a139);
  a96=(a112+a96);
  a154=(a154-a96);
  a96=(a55*a154);
  a155=(a7*a142);
  a96=(a96+a155);
  a155=(a5*a104);
  a96=(a96-a155);
  a155=(a10*a96);
  a153=(a153+a155);
  a151=(a151-a153);
  a153=(a63*a151);
  a133=(a133-a153);
  a1=(a1*a133);
  a0=sin(a0);
  a116=(a132*a116);
  a118=(a130*a118);
  a116=(a116-a118);
  a50=(a50*a136);
  a116=(a116+a50);
  a131=(a131*a134);
  a116=(a116-a131);
  a47=(a47*a102);
  a116=(a116+a47);
  a75=(a75*a39);
  a116=(a116-a75);
  a12=(a12*a137);
  a116=(a116+a12);
  a11=(a11*a82);
  a116=(a116+a11);
  a46=(a46*a54);
  a116=(a116+a46);
  a38=(a38*a124);
  a116=(a116+a38);
  a52=(a52*a100);
  a116=(a116+a52);
  a17=(a17*a129);
  a116=(a116+a17);
  a48=(a48*a120);
  a116=(a116-a48);
  a92=(a92*a49);
  a116=(a116-a92);
  a41=(a41*a123);
  a116=(a116+a41);
  a63=(a63*a53);
  a116=(a116+a63);
  a61=(a61*a151);
  a116=(a116+a61);
  a0=(a0*a116);
  a1=(a1-a0);
  if (res[0]!=0) res[0][3]=a1;
  a1=cos(a9);
  a0=(a2*a132);
  a116=(a13*a130);
  a0=(a0-a116);
  a0=(a0-a83);
  a116=(a0*a108);
  a61=(a44*a126);
  a63=(a32*a0);
  a61=(a61+a63);
  a61=(a94-a61);
  a61=(a61/a35);
  a63=(a61*a105);
  a116=(a116-a63);
  a63=(a126*a112);
  a116=(a116-a63);
  a63=(a40*a109);
  a116=(a116-a63);
  a63=(a2*a134);
  a41=(a26*a63);
  a116=(a116-a41);
  a41=(a13*a82);
  a92=(a2*a129);
  a41=(a41+a92);
  a92=(a83*a138);
  a41=(a41-a92);
  a92=(a16*a41);
  a116=(a116+a92);
  a92=(a18*a63);
  a48=(a10*a41);
  a92=(a92+a48);
  a48=(a15*a92);
  a116=(a116+a48);
  a48=(a13*a54);
  a17=(a2*a120);
  a48=(a48-a17);
  a17=(a81*a138);
  a48=(a48-a17);
  a17=(a37*a48);
  a116=(a116+a17);
  a17=(a93*a138);
  a116=(a116-a17);
  a82=(a2*a82);
  a129=(a13*a129);
  a82=(a82-a129);
  a129=(a83*a117);
  a82=(a82-a129);
  a129=(a8*a82);
  a116=(a116+a129);
  a74=(a74*a119);
  a116=(a116-a74);
  a74=(a122*a109);
  a129=(a126*a114);
  a74=(a74-a129);
  a129=(a44*a109);
  a17=(a32*a63);
  a129=(a129+a17);
  a17=(a129/a35);
  a74=(a74+a17);
  a45=(a94*a45);
  a74=(a74-a45);
  a45=(a2*a123);
  a17=(a13*a124);
  a45=(a45-a17);
  a83=(a83*a125);
  a45=(a45+a83);
  a83=(a36*a45);
  a74=(a74-a83);
  a83=(a18*a74);
  a17=(a27*a83);
  a116=(a116+a17);
  a17=(a42*a45);
  a116=(a116-a17);
  a17=(a18*a45);
  a52=(a10*a109);
  a17=(a17-a52);
  a52=(a19*a17);
  a116=(a116+a52);
  a52=(a84*a125);
  a116=(a116-a52);
  a52=(a62*a96);
  a116=(a116-a52);
  a52=(a33*a139);
  a52=(a115+a52);
  a100=(a27*a101);
  a52=(a52-a100);
  a100=(a55*a52);
  a38=(a76*a127);
  a46=(a56*a141);
  a38=(a38+a46);
  a140=(a22*a140);
  a38=(a38-a140);
  a140=(a78*a144);
  a38=(a38+a140);
  a73=(a20*a73);
  a38=(a38-a73);
  a73=(a71*a145);
  a38=(a38+a73);
  a100=(a100+a38);
  a73=(a57*a100);
  a116=(a116+a73);
  a73=(a59*a147);
  a116=(a116+a73);
  a1=(a1*a116);
  a9=sin(a9);
  a16=(a16*a63);
  a108=(a126*a108);
  a112=(a0*a112);
  a108=(a108+a112);
  a115=(a61*a115);
  a108=(a108+a115);
  a42=(a42*a109);
  a108=(a108+a42);
  a16=(a16-a108);
  a134=(a13*a134);
  a8=(a8*a134);
  a16=(a16-a8);
  a26=(a26*a41);
  a16=(a16+a26);
  a26=(a18*a41);
  a8=(a10*a63);
  a26=(a26-a8);
  a19=(a19*a26);
  a16=(a16+a19);
  a84=(a84*a138);
  a16=(a16+a84);
  a95=(a95*a119);
  a16=(a16-a95);
  a128=(a128/a35);
  a128=(a128*a125);
  a95=(a61/a35);
  a95=(a95*a113);
  a113=(a122/a35);
  a113=(a113*a129);
  a95=(a95+a113);
  a98=(a98/a35);
  a98=(a98*a138);
  a95=(a95+a98);
  a128=(a128-a95);
  a95=(a36/a35);
  a32=(a32*a41);
  a44=(a44*a45);
  a32=(a32+a44);
  a95=(a95*a32);
  a128=(a128+a95);
  a34=(a34*a128);
  a16=(a16+a34);
  a128=(a18*a128);
  a33=(a33*a128);
  a16=(a16+a33);
  a122=(a122*a63);
  a114=(a0*a114);
  a122=(a122-a114);
  a94=(a94*a51);
  a122=(a122+a94);
  a36=(a36*a41);
  a122=(a122-a36);
  a32=(a32/a35);
  a122=(a122-a32);
  a31=(a31*a122);
  a16=(a16+a31);
  a122=(a18*a122);
  a27=(a27*a122);
  a16=(a16+a27);
  a43=(a43*a74);
  a16=(a16+a43);
  a109=(a18*a109);
  a43=(a10*a45);
  a109=(a109+a43);
  a15=(a15*a109);
  a16=(a16-a15);
  a40=(a40*a45);
  a16=(a16+a40);
  a124=(a2*a124);
  a123=(a13*a123);
  a124=(a124+a123);
  a123=(a81*a125);
  a124=(a124-a123);
  a37=(a37*a124);
  a16=(a16+a37);
  a93=(a93*a125);
  a16=(a16-a93);
  a59=(a59*a96);
  a16=(a16+a59);
  a59=(a62*a147);
  a16=(a16+a59);
  a59=(a71*a101);
  a93=(a68*a127);
  a37=(a89*a127);
  a93=(a93+a37);
  a59=(a59-a93);
  a93=(a65*a144);
  a59=(a59-a93);
  a149=(a22*a149);
  a59=(a59+a149);
  a149=(a56*a106);
  a59=(a59-a149);
  a150=(a20*a150);
  a59=(a59-a150);
  a150=(a7*a59);
  a149=(a55*a105);
  a150=(a150-a149);
  a69=(a69*a141);
  a89=(a89*a141);
  a69=(a69-a89);
  a89=(a20*a101);
  a141=(a22*a141);
  a89=(a89-a141);
  a68=(a68*a89);
  a69=(a69+a68);
  a78=(a78*a101);
  a69=(a69-a78);
  a76=(a76*a106);
  a69=(a69+a76);
  a76=(a64*a106);
  a69=(a69-a76);
  a65=(a65*a145);
  a69=(a69-a65);
  a65=(a5*a69);
  a150=(a150-a65);
  a57=(a57*a150);
  a16=(a16+a57);
  a9=(a9*a16);
  a1=(a1-a9);
  if (res[0]!=0) res[0][4]=a1;
  a1=cos(a4);
  a54=(a2*a54);
  a120=(a13*a120);
  a54=(a54+a120);
  a120=(a81*a117);
  a54=(a54-a120);
  a120=(a6*a54);
  a130=(a2*a130);
  a132=(a13*a132);
  a130=(a130+a132);
  a130=(a130+a81);
  a130=(a130*a107);
  a120=(a120-a130);
  a82=(a10*a82);
  a134=(a18*a134);
  a82=(a82-a134);
  a134=(a80*a117);
  a82=(a82+a134);
  a134=(a7*a82);
  a120=(a120-a134);
  a134=(a5*a54);
  a130=(a7*a82);
  a134=(a134+a130);
  a134=(a3*a134);
  a120=(a120+a134);
  a134=(a66*a117);
  a120=(a120-a134);
  a134=(a91*a139);
  a120=(a120+a134);
  a134=(a5+a5);
  a130=(a88*a139);
  a128=(a18*a128);
  a130=(a130+a128);
  a134=(a134*a130);
  a120=(a120+a134);
  a48=(a10*a48);
  a124=(a18*a124);
  a48=(a48+a124);
  a124=(a7*a48);
  a120=(a120-a124);
  a124=(a14*a48);
  a120=(a120+a124);
  a124=(a90*a103);
  a120=(a120-a124);
  a124=(a86*a139);
  a134=(a25*a124);
  a61=(a18*a61);
  a61=(a61-a88);
  a128=(a61*a111);
  a135=(a87*a135);
  a128=(a128+a135);
  a134=(a134-a128);
  a128=(a30*a130);
  a134=(a134-a128);
  a128=(a29*a130);
  a122=(a18*a122);
  a83=(a10*a83);
  a122=(a122+a83);
  a88=(a88*a101);
  a122=(a122-a88);
  a88=(a21*a122);
  a128=(a128+a88);
  a88=(a128/a24);
  a134=(a134-a88);
  a88=(a7*a134);
  a120=(a120-a88);
  a88=(a28*a134);
  a120=(a120+a88);
  a97=(a97/a24);
  a97=(a97*a139);
  a61=(a29*a61);
  a88=(a10*a126);
  a83=(a18*a0);
  a88=(a88+a83);
  a88=(a88+a86);
  a83=(a21*a88);
  a61=(a61+a83);
  a61=(a87-a61);
  a61=(a61/a24);
  a61=(a61/a24);
  a61=(a61*a110);
  a97=(a97-a61);
  a85=(a85/a24);
  a85=(a85*a101);
  a97=(a97-a85);
  a85=(a30/a24);
  a85=(a85*a128);
  a97=(a97+a85);
  a85=(a25/a24);
  a29=(a29*a124);
  a26=(a18*a26);
  a17=(a10*a17);
  a26=(a26+a17);
  a86=(a86*a101);
  a26=(a26+a86);
  a21=(a21*a26);
  a29=(a29-a21);
  a85=(a85*a29);
  a97=(a97-a85);
  a23=(a23*a97);
  a120=(a120+a23);
  a23=(a5*a97);
  a23=(a22*a23);
  a120=(a120+a23);
  a87=(a87*a121);
  a88=(a88*a111);
  a87=(a87-a88);
  a30=(a30*a122);
  a87=(a87-a30);
  a25=(a25*a26);
  a87=(a87-a25);
  a29=(a29/a24);
  a87=(a87+a29);
  a87=(a20*a87);
  a120=(a120+a87);
  a87=(a5+a5);
  a92=(a10*a92);
  a109=(a18*a109);
  a92=(a92-a109);
  a109=(a80*a143);
  a92=(a92+a109);
  a87=(a87*a92);
  a120=(a120+a87);
  a87=(a79*a143);
  a120=(a120+a87);
  a87=(a70*a142);
  a120=(a120+a87);
  a87=(a72*a104);
  a120=(a120-a87);
  a87=(a55*a59);
  a120=(a120+a87);
  a87=(a58*a69);
  a120=(a120-a87);
  a1=(a1*a120);
  a4=sin(a4);
  a120=(a7+a7);
  a120=(a120*a54);
  a126=(a18*a126);
  a0=(a10*a0);
  a126=(a126-a0);
  a126=(a126-a80);
  a126=(a126*a107);
  a120=(a120-a126);
  a126=(a5*a82);
  a120=(a120-a126);
  a6=(a6*a82);
  a120=(a120+a6);
  a79=(a79*a117);
  a120=(a120-a79);
  a124=(a20*a124);
  a120=(a120-a124);
  a90=(a90*a139);
  a120=(a120-a90);
  a28=(a28*a130);
  a120=(a120+a28);
  a28=(a5*a48);
  a120=(a120-a28);
  a91=(a91*a103);
  a120=(a120-a91);
  a91=(a5*a134);
  a120=(a120-a91);
  a130=(a7*a130);
  a134=(a5*a134);
  a130=(a130+a134);
  a22=(a22*a130);
  a120=(a120+a22);
  a20=(a20*a122);
  a120=(a120+a20);
  a20=(a7+a7);
  a20=(a20*a97);
  a120=(a120+a20);
  a14=(a14*a92);
  a120=(a120+a14);
  a48=(a5*a48);
  a92=(a7*a92);
  a48=(a48+a92);
  a3=(a3*a48);
  a120=(a120+a3);
  a66=(a66*a143);
  a120=(a120-a66);
  a142=(a72*a142);
  a120=(a120+a142);
  a104=(a70*a104);
  a120=(a120+a104);
  a104=(a58*a59);
  a120=(a120+a104);
  a55=(a55*a69);
  a120=(a120+a55);
  a4=(a4*a120);
  a1=(a1-a4);
  if (res[0]!=0) res[0][5]=a1;
  a96=(a18*a96);
  a147=(a10*a147);
  a96=(a96+a147);
  a147=arg[4]? arg[4][0] : 0;
  a96=(a96+a147);
  if (res[0]!=0) res[0][6]=a96;
  a96=(a2*a53);
  a147=(a13*a151);
  a96=(a96-a147);
  a147=arg[4]? arg[4][1] : 0;
  a96=(a96+a147);
  if (res[0]!=0) res[0][7]=a96;
  a13=(a13*a53);
  a2=(a2*a151);
  a13=(a13+a2);
  a2=arg[4]? arg[4][2] : 0;
  a13=(a13+a2);
  if (res[0]!=0) res[0][8]=a13;
  a70=(a70*a99);
  a62=(a62*a152);
  a70=(a70-a62);
  a100=(a10*a100);
  a70=(a70+a100);
  a18=(a18*a150);
  a70=(a70+a18);
  a18=arg[4]? arg[4][3] : 0;
  a70=(a70+a18);
  if (res[0]!=0) res[0][9]=a70;
  a67=(a67*a52);
  a58=(a58*a105);
  a67=(a67-a58);
  a72=(a72*a154);
  a67=(a67+a72);
  a60=(a60*a148);
  a67=(a67+a60);
  a5=(a5*a59);
  a67=(a67+a5);
  a7=(a7*a69);
  a67=(a67+a7);
  a7=arg[4]? arg[4][4] : 0;
  a67=(a67+a7);
  if (res[0]!=0) res[0][10]=a67;
  a56=(a56*a89);
  a64=(a64*a127);
  a56=(a56-a64);
  a77=(a77*a144);
  a56=(a56-a77);
  a71=(a71*a146);
  a56=(a56-a71);
  a56=(a56+a38);
  a38=arg[4]? arg[4][5] : 0;
  a56=(a56+a38);
  if (res[0]!=0) res[0][11]=a56;
  if (res[1]!=0) res[1][0]=a125;
  if (res[1]!=0) res[1][1]=a39;
  if (res[1]!=0) res[1][2]=a49;
  if (res[1]!=0) res[1][3]=a119;
  if (res[1]!=0) res[1][4]=a103;
  a10=(a10*a119);
  a106=(a106-a10);
  if (res[1]!=0) res[1][5]=a106;
  return 0;
}

/* model_name_expl_vde_adj:(i0[12],i1[12],i2[6],i3[])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+168, *w13=w+180, *w16=w+186, *w17=w+198, *w18=w+210;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w7 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w8 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = input[0][9] */
  w9 = arg[0] ? arg[0][9] : 0;
  /* #10: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #11: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #12: @12 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11) */
  rr=w12;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #13: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #14: @1 = input[2][1] */
  w1 = arg[2] ? arg[2][1] : 0;
  /* #15: @2 = input[2][2] */
  w2 = arg[2] ? arg[2][2] : 0;
  /* #16: @3 = input[2][3] */
  w3 = arg[2] ? arg[2][3] : 0;
  /* #17: @4 = input[2][4] */
  w4 = arg[2] ? arg[2][4] : 0;
  /* #18: @5 = input[2][5] */
  w5 = arg[2] ? arg[2][5] : 0;
  /* #19: @13 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #20: @14 = 0x0 */
  /* #21: @15 = zeros(12x1,0nz) */
  /* #22: @16 = input[1][0] */
  casadi_copy(arg[1], 12, w16);
  /* #23: {@17, @18, NULL} = adj1_ForwardDyn(@12, @13, @14, @15, @16) */
  arg1[0]=w12;
  arg1[1]=w13;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=w16;
  res1[0]=w17;
  res1[1]=w18;
  res1[2]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #24: {@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11} = vertsplit(@17) */
  w0 = w17[0];
  w1 = w17[1];
  w2 = w17[2];
  w3 = w17[3];
  w4 = w17[4];
  w5 = w17[5];
  w6 = w17[6];
  w7 = w17[7];
  w8 = w17[8];
  w9 = w17[9];
  w10 = w17[10];
  w11 = w17[11];
  /* #25: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #26: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #27: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #28: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #29: output[0][4] = @4 */
  if (res[0]) res[0][4] = w4;
  /* #30: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  /* #31: output[0][6] = @6 */
  if (res[0]) res[0][6] = w6;
  /* #32: output[0][7] = @7 */
  if (res[0]) res[0][7] = w7;
  /* #33: output[0][8] = @8 */
  if (res[0]) res[0][8] = w8;
  /* #34: output[0][9] = @9 */
  if (res[0]) res[0][9] = w9;
  /* #35: output[0][10] = @10 */
  if (res[0]) res[0][10] = w10;
  /* #36: output[0][11] = @11 */
  if (res[0]) res[0][11] = w11;
  /* #37: {@11, @10, @9, @8, @7, @6} = vertsplit(@18) */
  w11 = w18[0];
  w10 = w18[1];
  w9 = w18[2];
  w8 = w18[3];
  w7 = w18[4];
  w6 = w18[5];
  /* #38: output[0][12] = @11 */
  if (res[0]) res[0][12] = w11;
  /* #39: output[0][13] = @10 */
  if (res[0]) res[0][13] = w10;
  /* #40: output[0][14] = @9 */
  if (res[0]) res[0][14] = w9;
  /* #41: output[0][15] = @8 */
  if (res[0]) res[0][15] = w8;
  /* #42: output[0][16] = @7 */
  if (res[0]) res[0][16] = w7;
  /* #43: output[0][17] = @6 */
  if (res[0]) res[0][17] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_name_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int model_name_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_name_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_name_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_name_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_name_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_name_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 216;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
