/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_name_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* adj1_ForwardDyn:(x[12],u[6],out_xdot[12x1,0nz],adj_xdot[12])->(adj_x[12],adj_u[6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a155, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=cos(a0);
  a2=cos(a0);
  a3=8.0000000000000004e-01;
  a4=arg[0]? arg[0][5] : 0;
  a5=sin(a4);
  a6=(a3*a5);
  a7=cos(a4);
  a8=(a6*a7);
  a9=(a7*a5);
  a8=(a8-a9);
  a9=arg[0]? arg[0][4] : 0;
  a10=sin(a9);
  a11=(a8*a10);
  a12=(a2*a11);
  a13=sin(a0);
  a14=(a3*a7);
  a15=(a14*a7);
  a16=casadi_sq(a5);
  a15=(a15+a16);
  a16=(a10*a15);
  a17=(a16*a10);
  a18=cos(a9);
  a19=1.;
  a20=5.0000000000000000e-01;
  a21=(a20*a5);
  a22=1.2500000000000000e+00;
  a23=(a22*a5);
  a24=(a23*a5);
  a25=casadi_sq(a7);
  a24=(a24+a25);
  a25=(a21/a24);
  a26=(a21*a25);
  a19=(a19-a26);
  a26=(a18*a19);
  a27=(a26*a18);
  a17=(a17+a27);
  a27=(a20*a7);
  a28=(a22*a7);
  a29=(a28*a5);
  a30=(a5*a7);
  a29=(a29-a30);
  a30=(a29/a24);
  a31=(a21*a30);
  a27=(a27-a31);
  a31=(a18*a27);
  a32=(a31*a18);
  a33=(a28*a7);
  a34=casadi_sq(a5);
  a33=(a33+a34);
  a34=(a29*a30);
  a33=(a33-a34);
  a34=(a18*a33);
  a35=(a34*a18);
  a36=(a32/a35);
  a37=(a32*a36);
  a17=(a17-a37);
  a37=(a13*a17);
  a12=(a12+a37);
  a37=(a14*a5);
  a38=(a5*a7);
  a37=(a37-a38);
  a38=(a18*a37);
  a39=(a38*a2);
  a40=(a10*a19);
  a41=(a40*a18);
  a42=(a18*a15);
  a43=(a42*a10);
  a41=(a41-a43);
  a43=(a10*a27);
  a44=(a43*a18);
  a45=(a44*a36);
  a41=(a41-a45);
  a45=(a41*a13);
  a39=(a39-a45);
  a45=(a38*a13);
  a46=(a41*a2);
  a45=(a45+a46);
  a46=(a6*a5);
  a47=casadi_sq(a7);
  a46=(a46+a47);
  a47=(a2*a46);
  a48=(a10*a37);
  a49=(a13*a48);
  a47=(a47+a49);
  a49=(a47*a13);
  a50=(a12*a2);
  a49=(a49-a50);
  a50=(a13*a46);
  a51=(a2*a48);
  a50=(a50-a51);
  a51=(a50*a13);
  a52=(a2*a17);
  a53=(a13*a11);
  a52=(a52-a53);
  a53=(a52*a2);
  a51=(a51+a53);
  a53=(a49/a51);
  a54=(a45*a53);
  a39=(a39-a54);
  a54=arg[1]? arg[1][1] : 0;
  a55=arg[0]? arg[0][10] : 0;
  a56=(a7*a55);
  a57=arg[0]? arg[0][9] : 0;
  a58=(a18*a57);
  a59=(a5*a58);
  a56=(a56-a59);
  a59=arg[0]? arg[0][6] : 0;
  a60=(a10*a59);
  a61=arg[0]? arg[0][8] : 0;
  a62=(a2*a61);
  a63=arg[0]? arg[0][7] : 0;
  a64=(a13*a63);
  a62=(a62-a64);
  a64=(a18*a62);
  a60=(a60+a64);
  a64=(a7*a58);
  a65=(a5*a55);
  a64=(a64+a65);
  a65=(a20*a64);
  a65=(a60+a65);
  a66=(a56*a65);
  a67=(a10*a57);
  a68=arg[0]? arg[0][11] : 0;
  a69=(a67+a68);
  a70=(a2*a63);
  a71=(a13*a61);
  a70=(a70+a71);
  a71=(a7*a70);
  a72=(a18*a59);
  a73=(a10*a62);
  a72=(a72-a73);
  a73=(a5*a72);
  a71=(a71-a73);
  a73=(a69*a71);
  a66=(a66-a73);
  a73=(a71*a68);
  a73=(a3*a73);
  a66=(a66+a73);
  a73=-5.0000000000000000e-01;
  a74=arg[1]? arg[1][5] : 0;
  a75=(a64*a56);
  a76=(a22*a64);
  a77=(a20*a60);
  a76=(a76+a77);
  a77=(a56*a76);
  a75=(a75-a77);
  a77=(a7*a72);
  a78=(a5*a70);
  a77=(a77+a78);
  a78=(a20*a69);
  a78=(a77-a78);
  a79=(a71*a78);
  a75=(a75-a79);
  a79=(a77*a71);
  a75=(a75+a79);
  a75=(a74-a75);
  a75=(a73*a75);
  a75=(a75/a22);
  a66=(a66+a75);
  a75=(a5*a66);
  a79=(a69*a78);
  a80=(a64*a65);
  a79=(a79-a80);
  a80=(a77*a68);
  a79=(a79-a80);
  a80=(a7*a79);
  a75=(a75+a80);
  a80=(a60*a55);
  a81=(a8*a80);
  a75=(a75-a81);
  a81=(a62*a57);
  a82=(a46*a81);
  a83=(a70*a57);
  a84=(a11*a83);
  a82=(a82+a84);
  a75=(a75+a82);
  a82=(a2*a75);
  a84=(a64*a71);
  a85=(a56*a78);
  a84=(a84-a85);
  a85=(a56*a68);
  a86=(a20*a85);
  a84=(a84+a86);
  a86=(a72*a55);
  a87=(a19*a86);
  a88=(a67*a55);
  a89=(a27*a88);
  a87=(a87-a89);
  a84=(a84+a87);
  a87=arg[1]? arg[1][4] : 0;
  a89=(a22*a69);
  a90=(a20*a77);
  a89=(a89-a90);
  a90=(a56*a89);
  a91=(a69*a56);
  a90=(a90-a91);
  a91=(a60*a71);
  a90=(a90-a91);
  a91=(a71*a65);
  a90=(a90+a91);
  a85=(a22*a85);
  a90=(a90+a85);
  a85=(a5*a90);
  a91=(a69*a76);
  a92=(a64*a89);
  a91=(a91-a92);
  a92=(a60*a78);
  a91=(a91+a92);
  a92=(a77*a65);
  a91=(a91-a92);
  a92=(a64*a68);
  a91=(a91-a92);
  a92=(a7*a91);
  a85=(a85+a92);
  a87=(a87-a85);
  a85=(a21*a87);
  a85=(a85/a24);
  a84=(a84+a85);
  a92=(a18*a84);
  a93=(a7*a66);
  a94=(a5*a79);
  a93=(a93-a94);
  a94=(a15*a80);
  a93=(a93-a94);
  a94=(a10*a93);
  a92=(a92-a94);
  a94=(a48*a81);
  a95=(a17*a83);
  a94=(a94+a95);
  a92=(a92-a94);
  a94=arg[1]? arg[1][3] : 0;
  a95=(a7*a90);
  a96=(a5*a91);
  a95=(a95-a96);
  a96=(a20*a7);
  a97=(a29*a25);
  a96=(a96-a97);
  a97=(a96*a86);
  a98=(a33*a88);
  a97=(a97-a98);
  a95=(a95+a97);
  a97=(a29*a87);
  a97=(a97/a24);
  a95=(a95+a97);
  a98=(a18*a95);
  a99=(a10*a74);
  a98=(a98+a99);
  a94=(a94-a98);
  a98=(a32*a94);
  a98=(a98/a35);
  a92=(a92+a98);
  a99=(a13*a92);
  a82=(a82-a99);
  a99=arg[1]? arg[1][2] : 0;
  a100=(a13*a75);
  a101=(a2*a92);
  a100=(a100+a101);
  a99=(a99-a100);
  a100=(a49*a99);
  a100=(a100/a51);
  a82=(a82+a100);
  a54=(a54-a82);
  a82=(a39*a54);
  a101=(a47*a2);
  a102=(a12*a13);
  a101=(a101+a102);
  a102=(a49*a53);
  a101=(a101-a102);
  a82=(a82/a101);
  a102=(a82/a101);
  a103=arg[3]? arg[3][6] : 0;
  a104=arg[3]? arg[3][11] : 0;
  a105=(a3*a104);
  a106=(a73*a105);
  a107=(a7*a106);
  a108=(a18*a107);
  a109=arg[3]? arg[3][10] : 0;
  a110=(a109/a24);
  a111=(a21*a110);
  a112=(a10*a111);
  a108=(a108+a112);
  a112=arg[3]? arg[3][9] : 0;
  a113=(a10*a104);
  a114=(a29*a110);
  a115=(a18*a114);
  a113=(a113+a115);
  a112=(a112-a113);
  a113=(a112/a35);
  a115=(a44*a113);
  a108=(a108+a115);
  a115=(a10*a107);
  a116=(a18*a111);
  a115=(a115-a116);
  a116=(a32*a113);
  a115=(a115-a116);
  a116=(a2*a115);
  a117=(a5*a106);
  a118=(a13*a117);
  a116=(a116-a118);
  a118=arg[3]? arg[3][8] : 0;
  a116=(a116+a118);
  a118=(a116/a51);
  a119=(a45*a118);
  a108=(a108+a119);
  a119=arg[3]? arg[3][7] : 0;
  a120=(a2*a117);
  a121=(a13*a115);
  a120=(a120+a121);
  a121=(a49*a118);
  a120=(a120+a121);
  a119=(a119-a120);
  a120=(a119/a101);
  a121=(a39*a120);
  a108=(a108+a121);
  a103=(a103-a108);
  a108=(a42*a18);
  a121=(a40*a10);
  a108=(a108+a121);
  a121=(a44/a35);
  a122=(a44*a121);
  a108=(a108-a122);
  a122=(a45/a51);
  a123=(a45*a122);
  a108=(a108-a123);
  a123=(a39/a101);
  a124=(a39*a123);
  a108=(a108-a124);
  a124=(a103/a108);
  a102=(a102*a124);
  a125=arg[1]? arg[1][0] : 0;
  a126=(a18*a93);
  a127=(a10*a84);
  a126=(a126+a127);
  a127=(a38*a81);
  a128=(a41*a83);
  a127=(a127-a128);
  a126=(a126+a127);
  a127=(a44*a94);
  a127=(a127/a35);
  a126=(a126+a127);
  a128=(a45*a99);
  a128=(a128/a51);
  a126=(a126+a128);
  a126=(a126+a82);
  a125=(a125-a126);
  a126=9.8100000000000005e+00;
  a82=(a8*a18);
  a129=(a13*a82);
  a130=(a26*a10);
  a131=(a16*a18);
  a130=(a130-a131);
  a131=(a32*a121);
  a130=(a130-a131);
  a131=(a2*a130);
  a129=(a129+a131);
  a129=(a129-a45);
  a131=(a50*a2);
  a132=(a52*a13);
  a131=(a131-a132);
  a131=(a131-a49);
  a132=(a131*a123);
  a129=(a129-a132);
  a129=(a126*a129);
  a125=(a125-a129);
  a125=(a125/a108);
  a129=(a39*a125);
  a132=(a126*a131);
  a129=(a129+a132);
  a129=(a54-a129);
  a129=(a129/a101);
  a132=(a129/a101);
  a132=(a132*a119);
  a119=(a123/a101);
  a108=(a125/a108);
  a108=(a108*a103);
  a103=(a39*a108);
  a133=(a126*a124);
  a131=(a131*a133);
  a103=(a103+a131);
  a119=(a119*a103);
  a132=(a132+a119);
  a102=(a102-a132);
  a132=(a12*a102);
  a119=(a45*a125);
  a131=(a49*a129);
  a119=(a119+a131);
  a131=(a126*a51);
  a119=(a119+a131);
  a119=(a99-a119);
  a119=(a119/a51);
  a131=(a126+a119);
  a134=(a131*a117);
  a135=(a129*a115);
  a134=(a134+a135);
  a135=(a123*a133);
  a136=(a126*a120);
  a135=(a135-a136);
  a136=(a52*a135);
  a134=(a134+a136);
  a82=(a82*a133);
  a134=(a134+a82);
  a132=(a132-a134);
  a134=(a124/a101);
  a39=(a39*a134);
  a39=(a120-a39);
  a82=(a92*a39);
  a132=(a132+a82);
  a82=(a13*a102);
  a136=(a129*a118);
  a136=(a136+a135);
  a137=(a53*a102);
  a136=(a136+a137);
  a137=(a39/a51);
  a138=(a99*a137);
  a136=(a136+a138);
  a138=(a49*a102);
  a123=(a123*a108);
  a120=(a125*a120);
  a123=(a123-a120);
  a103=(a103/a101);
  a123=(a123+a103);
  a54=(a54*a134);
  a123=(a123-a54);
  a54=(a45*a123);
  a138=(a138+a54);
  a54=(a138/a51);
  a136=(a136+a54);
  a54=(a2*a136);
  a82=(a82+a54);
  a54=(a17*a82);
  a132=(a132+a54);
  a54=(a47*a136);
  a132=(a132-a54);
  a54=(a2*a102);
  a134=(a13*a136);
  a54=(a54-a134);
  a134=(a48*a54);
  a132=(a132+a134);
  a134=(a41*a123);
  a132=(a132-a134);
  a100=(a100/a51);
  a100=(a100*a39);
  a119=(a119/a51);
  a119=(a119*a116);
  a126=(a126*a118);
  a119=(a119+a126);
  a126=(a122/a51);
  a116=(a45*a108);
  a126=(a126*a116);
  a119=(a119+a126);
  a100=(a100-a119);
  a119=(a53/a51);
  a119=(a119*a138);
  a100=(a100+a119);
  a128=(a128/a51);
  a128=(a128*a124);
  a100=(a100+a128);
  a128=(a2*a100);
  a119=(a13*a135);
  a128=(a128-a119);
  a119=(a11*a128);
  a132=(a132-a119);
  a119=(a50*a100);
  a132=(a132+a119);
  a119=(a2*a135);
  a138=(a13*a100);
  a119=(a119+a138);
  a138=(a46*a119);
  a132=(a132+a138);
  a49=(a49*a137);
  a49=(a118-a49);
  a137=(a124/a51);
  a45=(a45*a137);
  a49=(a49-a45);
  a45=(a75*a49);
  a132=(a132-a45);
  a122=(a122*a108);
  a118=(a125*a118);
  a122=(a122-a118);
  a116=(a116/a51);
  a122=(a122+a116);
  a122=(a122+a133);
  a53=(a53*a123);
  a122=(a122-a53);
  a99=(a99*a137);
  a122=(a122-a99);
  a99=(a38*a122);
  a132=(a132+a99);
  a99=(a41*a124);
  a137=(a13*a39);
  a53=(a2*a49);
  a137=(a137-a53);
  a53=(a17*a137);
  a53=(a115+a53);
  a116=(a2*a39);
  a51=(a13*a49);
  a116=(a116+a51);
  a51=(a11*a116);
  a53=(a53+a51);
  a99=(a99-a53);
  a53=(a57*a99);
  a51=(a137/a35);
  a118=(a32*a51);
  a118=(a113+a118);
  a45=(a124/a35);
  a138=(a44*a45);
  a118=(a118-a138);
  a138=(a18*a118);
  a126=(a5*a138);
  a134=(a138/a24);
  a103=(a29*a134);
  a103=(a110-a103);
  a101=(a18*a137);
  a120=(a10*a124);
  a101=(a101-a120);
  a120=(a101/a24);
  a139=(a21*a120);
  a103=(a103+a139);
  a139=(a7*a103);
  a126=(a126-a139);
  a139=(a64*a126);
  a140=(a7*a138);
  a141=(a5*a103);
  a140=(a140+a141);
  a141=(a56*a140);
  a139=(a139+a141);
  a141=(a20*a139);
  a142=(a65*a126);
  a141=(a141-a142);
  a142=(a10*a137);
  a143=(a18*a124);
  a142=(a142+a143);
  a143=(a5*a142);
  a144=(a7*a116);
  a143=(a143-a144);
  a144=(a68*a143);
  a141=(a141-a144);
  a144=(a5*a116);
  a145=(a7*a142);
  a144=(a144+a145);
  a145=(a3*a144);
  a73=(a73*a145);
  a105=(a105-a73);
  a73=(a71*a105);
  a141=(a141-a73);
  a73=(a60*a126);
  a145=(a56*a101);
  a73=(a73-a145);
  a145=(a69*a143);
  a73=(a73+a145);
  a145=(a71*a105);
  a73=(a73+a145);
  a141=(a141+a73);
  a145=(a5*a141);
  a53=(a53+a145);
  a145=(a60*a140);
  a146=(a65*a140);
  a145=(a145-a146);
  a146=(a64*a101);
  a145=(a145+a146);
  a146=(a77*a105);
  a145=(a145-a146);
  a146=(a78*a105);
  a145=(a145+a146);
  a146=(a3*a144);
  a146=(a106+a146);
  a147=(a68*a146);
  a145=(a145-a147);
  a147=(a69*a144);
  a145=(a145+a147);
  a147=(a7*a145);
  a53=(a53+a147);
  a147=(a61*a53);
  a132=(a132+a147);
  a147=(a78*a126);
  a148=(a71*a140);
  a147=(a147+a148);
  a148=(a8*a116);
  a148=(a107+a148);
  a149=(a15*a142);
  a148=(a148+a149);
  a149=(a55*a148);
  a147=(a147+a149);
  a149=(a69*a126);
  a150=(a56*a105);
  a149=(a149+a150);
  a150=(a20*a149);
  a147=(a147+a150);
  a150=(a77*a126);
  a151=(a71*a140);
  a150=(a150+a151);
  a151=(a64*a143);
  a150=(a150+a151);
  a151=(a56*a144);
  a150=(a150+a151);
  a147=(a147-a150);
  a151=(a18*a147);
  a152=(a48*a137);
  a152=(a117+a152);
  a153=(a46*a116);
  a152=(a152+a153);
  a153=(a38*a124);
  a152=(a152+a153);
  a153=(a57*a152);
  a154=(a19*a101);
  a96=(a96*a138);
  a96=(a111+a96);
  a154=(a154-a96);
  a96=(a55*a154);
  a155=(a7*a141);
  a96=(a96+a155);
  a155=(a5*a145);
  a96=(a96-a155);
  a155=(a10*a96);
  a153=(a153+a155);
  a151=(a151-a153);
  a153=(a63*a151);
  a132=(a132-a153);
  a1=(a1*a132);
  a0=sin(a0);
  a115=(a131*a115);
  a117=(a129*a117);
  a115=(a115-a117);
  a50=(a50*a135);
  a115=(a115+a50);
  a130=(a130*a133);
  a115=(a115-a130);
  a47=(a47*a102);
  a115=(a115+a47);
  a75=(a75*a39);
  a115=(a115-a75);
  a12=(a12*a136);
  a115=(a115+a12);
  a11=(a11*a82);
  a115=(a115+a11);
  a46=(a46*a54);
  a115=(a115+a46);
  a38=(a38*a123);
  a115=(a115+a38);
  a52=(a52*a100);
  a115=(a115+a52);
  a17=(a17*a128);
  a115=(a115+a17);
  a48=(a48*a119);
  a115=(a115-a48);
  a92=(a92*a49);
  a115=(a115-a92);
  a41=(a41*a122);
  a115=(a115+a41);
  a63=(a63*a53);
  a115=(a115+a63);
  a61=(a61*a151);
  a115=(a115+a61);
  a0=(a0*a115);
  a1=(a1-a0);
  if (res[0]!=0) res[0][3]=a1;
  a1=cos(a9);
  a0=(a2*a131);
  a115=(a13*a129);
  a0=(a0-a115);
  a0=(a0-a83);
  a115=(a0*a107);
  a61=(a44*a125);
  a63=(a32*a0);
  a61=(a61+a63);
  a61=(a94-a61);
  a61=(a61/a35);
  a63=(a61*a104);
  a115=(a115-a63);
  a63=(a125*a111);
  a115=(a115-a63);
  a63=(a40*a108);
  a115=(a115-a63);
  a63=(a2*a133);
  a41=(a26*a63);
  a115=(a115-a41);
  a41=(a13*a82);
  a92=(a2*a128);
  a41=(a41+a92);
  a92=(a83*a137);
  a41=(a41-a92);
  a92=(a16*a41);
  a115=(a115+a92);
  a92=(a18*a63);
  a48=(a10*a41);
  a92=(a92+a48);
  a48=(a15*a92);
  a115=(a115+a48);
  a48=(a13*a54);
  a17=(a2*a119);
  a48=(a48-a17);
  a17=(a81*a137);
  a48=(a48-a17);
  a17=(a37*a48);
  a115=(a115+a17);
  a17=(a93*a137);
  a115=(a115-a17);
  a82=(a2*a82);
  a128=(a13*a128);
  a82=(a82-a128);
  a128=(a83*a116);
  a82=(a82-a128);
  a128=(a8*a82);
  a115=(a115+a128);
  a74=(a74*a118);
  a115=(a115-a74);
  a74=(a121*a108);
  a128=(a125*a113);
  a74=(a74-a128);
  a128=(a44*a108);
  a17=(a32*a63);
  a128=(a128+a17);
  a17=(a128/a35);
  a74=(a74+a17);
  a45=(a94*a45);
  a74=(a74-a45);
  a45=(a2*a122);
  a17=(a13*a123);
  a45=(a45-a17);
  a83=(a83*a124);
  a45=(a45+a83);
  a83=(a36*a45);
  a74=(a74-a83);
  a83=(a18*a74);
  a17=(a27*a83);
  a115=(a115+a17);
  a17=(a42*a45);
  a115=(a115-a17);
  a17=(a18*a45);
  a52=(a10*a108);
  a17=(a17-a52);
  a52=(a19*a17);
  a115=(a115+a52);
  a52=(a84*a124);
  a115=(a115-a52);
  a52=(a62*a96);
  a115=(a115-a52);
  a52=(a33*a138);
  a52=(a114+a52);
  a100=(a27*a101);
  a52=(a52-a100);
  a100=(a55*a52);
  a38=(a76*a126);
  a46=(a56*a140);
  a38=(a38+a46);
  a139=(a22*a139);
  a38=(a38-a139);
  a139=(a78*a143);
  a38=(a38+a139);
  a73=(a20*a73);
  a38=(a38-a73);
  a73=(a71*a144);
  a38=(a38+a73);
  a100=(a100+a38);
  a73=(a57*a100);
  a115=(a115+a73);
  a73=(a59*a147);
  a115=(a115+a73);
  a1=(a1*a115);
  a9=sin(a9);
  a16=(a16*a63);
  a107=(a125*a107);
  a111=(a0*a111);
  a107=(a107+a111);
  a114=(a61*a114);
  a107=(a107+a114);
  a42=(a42*a108);
  a107=(a107+a42);
  a16=(a16-a107);
  a133=(a13*a133);
  a8=(a8*a133);
  a16=(a16-a8);
  a26=(a26*a41);
  a16=(a16+a26);
  a26=(a18*a41);
  a8=(a10*a63);
  a26=(a26-a8);
  a19=(a19*a26);
  a16=(a16+a19);
  a84=(a84*a137);
  a16=(a16+a84);
  a95=(a95*a118);
  a16=(a16-a95);
  a127=(a127/a35);
  a127=(a127*a124);
  a95=(a61/a35);
  a95=(a95*a112);
  a112=(a121/a35);
  a112=(a112*a128);
  a95=(a95+a112);
  a98=(a98/a35);
  a98=(a98*a137);
  a95=(a95+a98);
  a127=(a127-a95);
  a95=(a36/a35);
  a32=(a32*a41);
  a44=(a44*a45);
  a32=(a32+a44);
  a95=(a95*a32);
  a127=(a127+a95);
  a34=(a34*a127);
  a16=(a16+a34);
  a127=(a18*a127);
  a33=(a33*a127);
  a16=(a16+a33);
  a121=(a121*a63);
  a113=(a0*a113);
  a121=(a121-a113);
  a94=(a94*a51);
  a121=(a121+a94);
  a36=(a36*a41);
  a121=(a121-a36);
  a32=(a32/a35);
  a121=(a121-a32);
  a31=(a31*a121);
  a16=(a16+a31);
  a121=(a18*a121);
  a27=(a27*a121);
  a16=(a16+a27);
  a43=(a43*a74);
  a16=(a16+a43);
  a108=(a18*a108);
  a43=(a10*a45);
  a108=(a108+a43);
  a15=(a15*a108);
  a16=(a16-a15);
  a40=(a40*a45);
  a16=(a16+a40);
  a123=(a2*a123);
  a122=(a13*a122);
  a123=(a123+a122);
  a122=(a81*a124);
  a123=(a123-a122);
  a37=(a37*a123);
  a16=(a16+a37);
  a93=(a93*a124);
  a16=(a16-a93);
  a59=(a59*a96);
  a16=(a16+a59);
  a59=(a62*a147);
  a16=(a16+a59);
  a59=(a71*a101);
  a93=(a68*a126);
  a37=(a89*a126);
  a93=(a93+a37);
  a59=(a59-a93);
  a93=(a65*a143);
  a59=(a59-a93);
  a149=(a22*a149);
  a59=(a59+a149);
  a149=(a56*a105);
  a59=(a59-a149);
  a150=(a20*a150);
  a59=(a59-a150);
  a150=(a7*a59);
  a149=(a55*a104);
  a150=(a150-a149);
  a69=(a69*a140);
  a89=(a89*a140);
  a69=(a69-a89);
  a89=(a20*a101);
  a140=(a22*a140);
  a89=(a89-a140);
  a68=(a68*a89);
  a69=(a69+a68);
  a78=(a78*a101);
  a69=(a69-a78);
  a76=(a76*a105);
  a69=(a69+a76);
  a76=(a64*a105);
  a69=(a69-a76);
  a65=(a65*a144);
  a69=(a69-a65);
  a65=(a5*a69);
  a150=(a150-a65);
  a57=(a57*a150);
  a16=(a16+a57);
  a9=(a9*a16);
  a1=(a1-a9);
  if (res[0]!=0) res[0][4]=a1;
  a1=cos(a4);
  a54=(a2*a54);
  a119=(a13*a119);
  a54=(a54+a119);
  a119=(a81*a116);
  a54=(a54-a119);
  a119=(a6*a54);
  a129=(a2*a129);
  a131=(a13*a131);
  a129=(a129+a131);
  a129=(a129+a81);
  a129=(a129*a106);
  a119=(a119-a129);
  a82=(a10*a82);
  a133=(a18*a133);
  a82=(a82-a133);
  a133=(a80*a116);
  a82=(a82+a133);
  a133=(a7*a82);
  a119=(a119-a133);
  a133=(a5*a54);
  a129=(a7*a82);
  a133=(a133+a129);
  a133=(a3*a133);
  a119=(a119+a133);
  a133=(a66*a116);
  a119=(a119-a133);
  a133=(a91*a138);
  a119=(a119+a133);
  a133=(a5+a5);
  a129=(a88*a138);
  a127=(a18*a127);
  a129=(a129+a127);
  a133=(a133*a129);
  a119=(a119+a133);
  a48=(a10*a48);
  a123=(a18*a123);
  a48=(a48+a123);
  a123=(a7*a48);
  a119=(a119-a123);
  a123=(a14*a48);
  a119=(a119+a123);
  a123=(a90*a103);
  a119=(a119-a123);
  a123=(a86*a138);
  a133=(a25*a123);
  a61=(a18*a61);
  a61=(a61-a88);
  a127=(a61*a110);
  a134=(a87*a134);
  a127=(a127+a134);
  a133=(a133-a127);
  a127=(a30*a129);
  a133=(a133-a127);
  a127=(a29*a129);
  a121=(a18*a121);
  a83=(a10*a83);
  a121=(a121+a83);
  a88=(a88*a101);
  a121=(a121-a88);
  a88=(a21*a121);
  a127=(a127+a88);
  a88=(a127/a24);
  a133=(a133-a88);
  a88=(a7*a133);
  a119=(a119-a88);
  a88=(a28*a133);
  a119=(a119+a88);
  a97=(a97/a24);
  a97=(a97*a138);
  a61=(a29*a61);
  a88=(a10*a125);
  a83=(a18*a0);
  a88=(a88+a83);
  a88=(a88+a86);
  a83=(a21*a88);
  a61=(a61+a83);
  a61=(a87-a61);
  a61=(a61/a24);
  a61=(a61/a24);
  a61=(a61*a109);
  a97=(a97-a61);
  a85=(a85/a24);
  a85=(a85*a101);
  a97=(a97-a85);
  a85=(a30/a24);
  a85=(a85*a127);
  a97=(a97+a85);
  a85=(a25/a24);
  a29=(a29*a123);
  a26=(a18*a26);
  a17=(a10*a17);
  a26=(a26+a17);
  a86=(a86*a101);
  a26=(a26+a86);
  a21=(a21*a26);
  a29=(a29-a21);
  a85=(a85*a29);
  a97=(a97-a85);
  a23=(a23*a97);
  a119=(a119+a23);
  a23=(a5*a97);
  a23=(a22*a23);
  a119=(a119+a23);
  a87=(a87*a120);
  a88=(a88*a110);
  a87=(a87-a88);
  a30=(a30*a121);
  a87=(a87-a30);
  a25=(a25*a26);
  a87=(a87-a25);
  a29=(a29/a24);
  a87=(a87+a29);
  a87=(a20*a87);
  a119=(a119+a87);
  a87=(a5+a5);
  a92=(a10*a92);
  a108=(a18*a108);
  a92=(a92-a108);
  a108=(a80*a142);
  a92=(a92+a108);
  a87=(a87*a92);
  a119=(a119+a87);
  a87=(a79*a142);
  a119=(a119+a87);
  a87=(a70*a141);
  a119=(a119+a87);
  a87=(a72*a145);
  a119=(a119-a87);
  a87=(a55*a59);
  a119=(a119+a87);
  a87=(a58*a69);
  a119=(a119-a87);
  a1=(a1*a119);
  a4=sin(a4);
  a119=(a7+a7);
  a119=(a119*a54);
  a125=(a18*a125);
  a0=(a10*a0);
  a125=(a125-a0);
  a125=(a125-a80);
  a125=(a125*a106);
  a119=(a119-a125);
  a125=(a5*a82);
  a119=(a119-a125);
  a6=(a6*a82);
  a119=(a119+a6);
  a79=(a79*a116);
  a119=(a119-a79);
  a123=(a20*a123);
  a119=(a119-a123);
  a90=(a90*a138);
  a119=(a119-a90);
  a28=(a28*a129);
  a119=(a119+a28);
  a28=(a5*a48);
  a119=(a119-a28);
  a91=(a91*a103);
  a119=(a119-a91);
  a91=(a5*a133);
  a119=(a119-a91);
  a129=(a7*a129);
  a133=(a5*a133);
  a129=(a129+a133);
  a22=(a22*a129);
  a119=(a119+a22);
  a20=(a20*a121);
  a119=(a119+a20);
  a20=(a7+a7);
  a20=(a20*a97);
  a119=(a119+a20);
  a14=(a14*a92);
  a119=(a119+a14);
  a48=(a5*a48);
  a92=(a7*a92);
  a48=(a48+a92);
  a3=(a3*a48);
  a119=(a119+a3);
  a66=(a66*a142);
  a119=(a119-a66);
  a141=(a72*a141);
  a119=(a119+a141);
  a145=(a70*a145);
  a119=(a119+a145);
  a145=(a58*a59);
  a119=(a119+a145);
  a55=(a55*a69);
  a119=(a119+a55);
  a4=(a4*a119);
  a1=(a1-a4);
  if (res[0]!=0) res[0][5]=a1;
  a96=(a18*a96);
  a147=(a10*a147);
  a96=(a96+a147);
  a147=arg[3]? arg[3][0] : 0;
  a96=(a96+a147);
  if (res[0]!=0) res[0][6]=a96;
  a96=(a2*a53);
  a147=(a13*a151);
  a96=(a96-a147);
  a147=arg[3]? arg[3][1] : 0;
  a96=(a96+a147);
  if (res[0]!=0) res[0][7]=a96;
  a13=(a13*a53);
  a2=(a2*a151);
  a13=(a13+a2);
  a2=arg[3]? arg[3][2] : 0;
  a13=(a13+a2);
  if (res[0]!=0) res[0][8]=a13;
  a70=(a70*a99);
  a62=(a62*a152);
  a70=(a70-a62);
  a100=(a10*a100);
  a70=(a70+a100);
  a18=(a18*a150);
  a70=(a70+a18);
  a18=arg[3]? arg[3][3] : 0;
  a70=(a70+a18);
  if (res[0]!=0) res[0][9]=a70;
  a67=(a67*a52);
  a58=(a58*a104);
  a67=(a67-a58);
  a72=(a72*a154);
  a67=(a67+a72);
  a60=(a60*a148);
  a67=(a67+a60);
  a5=(a5*a59);
  a67=(a67+a5);
  a7=(a7*a69);
  a67=(a67+a7);
  a7=arg[3]? arg[3][4] : 0;
  a67=(a67+a7);
  if (res[0]!=0) res[0][10]=a67;
  a56=(a56*a89);
  a64=(a64*a126);
  a56=(a56-a64);
  a77=(a77*a143);
  a56=(a56-a77);
  a71=(a71*a146);
  a56=(a56-a71);
  a56=(a56+a38);
  a38=arg[3]? arg[3][5] : 0;
  a56=(a56+a38);
  if (res[0]!=0) res[0][11]=a56;
  if (res[1]!=0) res[1][0]=a124;
  if (res[1]!=0) res[1][1]=a39;
  if (res[1]!=0) res[1][2]=a49;
  if (res[1]!=0) res[1][3]=a118;
  if (res[1]!=0) res[1][4]=a103;
  a10=(a10*a118);
  a105=(a105-a10);
  if (res[1]!=0) res[1][5]=a105;
  return 0;
}

/* model_name_expl_vde_adj:(i0[12],i1[12],i2[6],i3[])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+168, *w13=w+180, *w15=w+186, *w16=w+198, *w17=w+210;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w7 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w8 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = input[0][9] */
  w9 = arg[0] ? arg[0][9] : 0;
  /* #10: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #11: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #12: @12 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11) */
  rr=w12;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #13: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #14: @1 = input[2][1] */
  w1 = arg[2] ? arg[2][1] : 0;
  /* #15: @2 = input[2][2] */
  w2 = arg[2] ? arg[2][2] : 0;
  /* #16: @3 = input[2][3] */
  w3 = arg[2] ? arg[2][3] : 0;
  /* #17: @4 = input[2][4] */
  w4 = arg[2] ? arg[2][4] : 0;
  /* #18: @5 = input[2][5] */
  w5 = arg[2] ? arg[2][5] : 0;
  /* #19: @13 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #20: @14 = zeros(12x1,0nz) */
  /* #21: @15 = input[1][0] */
  casadi_copy(arg[1], 12, w15);
  /* #22: {@16, @17} = adj1_ForwardDyn(@12, @13, @14, @15) */
  arg1[0]=w12;
  arg1[1]=w13;
  arg1[2]=0;
  arg1[3]=w15;
  res1[0]=w16;
  res1[1]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #23: {@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11} = vertsplit(@16) */
  w0 = w16[0];
  w1 = w16[1];
  w2 = w16[2];
  w3 = w16[3];
  w4 = w16[4];
  w5 = w16[5];
  w6 = w16[6];
  w7 = w16[7];
  w8 = w16[8];
  w9 = w16[9];
  w10 = w16[10];
  w11 = w16[11];
  /* #24: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #25: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #26: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #27: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #28: output[0][4] = @4 */
  if (res[0]) res[0][4] = w4;
  /* #29: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  /* #30: output[0][6] = @6 */
  if (res[0]) res[0][6] = w6;
  /* #31: output[0][7] = @7 */
  if (res[0]) res[0][7] = w7;
  /* #32: output[0][8] = @8 */
  if (res[0]) res[0][8] = w8;
  /* #33: output[0][9] = @9 */
  if (res[0]) res[0][9] = w9;
  /* #34: output[0][10] = @10 */
  if (res[0]) res[0][10] = w10;
  /* #35: output[0][11] = @11 */
  if (res[0]) res[0][11] = w11;
  /* #36: {@11, @10, @9, @8, @7, @6} = vertsplit(@17) */
  w11 = w17[0];
  w10 = w17[1];
  w9 = w17[2];
  w8 = w17[3];
  w7 = w17[4];
  w6 = w17[5];
  /* #37: output[0][12] = @11 */
  if (res[0]) res[0][12] = w11;
  /* #38: output[0][13] = @10 */
  if (res[0]) res[0][13] = w10;
  /* #39: output[0][14] = @9 */
  if (res[0]) res[0][14] = w9;
  /* #40: output[0][15] = @8 */
  if (res[0]) res[0][15] = w8;
  /* #41: output[0][16] = @7 */
  if (res[0]) res[0][16] = w7;
  /* #42: output[0][17] = @6 */
  if (res[0]) res[0][17] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_name_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_name_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int model_name_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_name_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_name_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_name_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_name_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_name_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_name_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 216;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
